# Generated by Django 5.0.1 on 2024-01-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('estoque', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('tamanho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('valor_receber', models.FloatField(default=0)),
                ('freezer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.freezer')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Entrada', max_length=10)),
                ('data', models.DateField(default='2023-01-01')),
                ('valor_recebido_pagamento', models.FloatField(default=0)),
                ('desconto', models.FloatField()),
                ('juros', models.FloatField()),
                ('tipo_pagamento', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=20)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('C', 'Cubo'), ('T', 'Triturado')], max_length=1)),
                ('valor_unitario', models.FloatField()),
                ('estoque', models.IntegerField()),
                ('kg', models.IntegerField(default=0)),
                ('embalagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.embalagem')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.FloatField()),
                ('valor_pedido', models.FloatField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('boleto', models.BooleanField(blank=True, default=False, null=True)),
                ('status_pago', models.CharField(choices=[('A', 'Em aberto'), ('R', 'Recebido'), ('C', 'Cancelado'), ('RP', 'Recebido Parcialmente')], default='A', max_length=2)),
                ('valor_total', models.FloatField(default=0)),
                ('valor_receber', models.FloatField(default=0)),
                ('valor_recebido', models.FloatField(default=0)),
                ('prazo', models.CharField(max_length=20)),
                ('nfe', models.BooleanField(blank=True, default=False, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.cliente')),
                ('pagamento', models.ManyToManyField(to='vendas.pagamentovenda')),
                ('produto', models.ManyToManyField(to='vendas.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(max_length=20)),
                ('prazo', models.BooleanField()),
                ('data_prevista', models.DateField()),
                ('valor', models.FloatField()),
                ('obs', models.CharField(max_length=40, null=True)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.venda')),
            ],
        ),
    ]
