# Generated by Django 5.0.1 on 2024-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoprazo',
            name='desconto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='juros',
            field=models.FloatField(default=0),
        ),
    ]
