# Generated by Django 5.0.1 on 2024-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_pagamentoprazo_desconto_alter_pagamentovenda_juros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='cliente',
            field=models.CharField(max_length=30),
        ),
    ]
