# Generated by Django 5.0.1 on 2024-01-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('data_parcela', models.DateField()),
                ('parcela', models.IntegerField(default=1)),
                ('quantidade_parcelas', models.IntegerField(default=1)),
                ('loja', models.CharField(max_length=30)),
                ('produto', models.CharField(max_length=20)),
                ('valor', models.FloatField(default=0)),
                ('tipo_conta', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Saida', max_length=10)),
                ('data', models.DateField()),
                ('categoria', models.CharField(max_length=30)),
                ('subcategoria', models.CharField(max_length=30, null=True)),
                ('valor', models.FloatField()),
                ('tipo_pagamento', models.CharField(max_length=20)),
                ('obs', models.CharField(max_length=100, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subcategoria', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoriadespesa')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('categoria_transferencia', models.CharField(default='Transferencia', max_length=30)),
                ('valor', models.FloatField()),
                ('tipo_transferencia', models.CharField(max_length=20)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.conta')),
            ],
        ),
    ]
