# Generated by Django 5.0.1 on 2024-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='tipo_conta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
